name: Close Issues from Non-Owners
on:
  issues:
    types: [opened]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is not an owner
        if: github.event.issue.user.login != github.repository_owner
        run: |
          gh issue close ${{ github.event.issue.number }}
          gh issue comment ${{ github.event.issue.number }} --body "Only repository owners can create issues."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
